### ISSUE TITLE
"Add People" button missing in UICloudSharingController for existing share on iOS 15

### ISSUE THREAD

**Issue by mmklug** [apple/cloudkit-sample-sharing#11]
Tapping on a previously shared contact's share button presents the People view (UICloudSharingController).
When running on iOS 15 (and also on iOS 15.1 beta 2), the "Add People" button is missing, so it's not possible to add new people.
Works fine when running on iOS 14.8.

To reproduce:
1) create a new contact
2) share the contact to a user tapping on the contact’s share button
3) try to share the contact to another user tapping again on the contact’s share button
Expected behaviour: People screen appears showing the current two users (owner and share) plus “Add People” button
Actual behaviour on iOS 15: “Add People” button is missing (on iOS 15)
On iOS 14.8 actual behaviour is as expected.

**Comment by sjrmanning** [comment]
Thanks for calling this out. Can you please file a Feedback via Feedback Assistant? This will help bring attention to the issue and prioritize a fix.

**Comment by mmklug** [comment]
> Thanks for calling this out. Can you please file a Feedback via Feedback Assistant? This will help bring attention to the issue and prioritize a fix.

Thanks. Feedback FB9668067 was filed on Sep 30.

**Comment by sjrmanning** [comment]
This issue has been fixed in iOS 15.2. Let us know if you have any further issues and thanks for the feedback!
