### ISSUE TITLE
Right  off of  GitHub the  UnitTest Fail...

### ISSUE THREAD

**Issue by davidakoontz** [apple/cloudkit-sample-sharing#14]
Just  cloned the  repo  to  brush up  on  CloudKit before WWDC22 and the  simple sharing app  does NOT  pass it's own  unit test... it won't  compile.  Oh-it hurts my heart  to point out such bad coding practices  are the norm at Apple I guess.

I come from the XP era of Don't Break The  Build!

func  tearDownWithError()...
 ...
  async {
            _ = try await database.modifyRecords(deleting: idsToDelete)   //[Missing argument for  parm 'saving']
            
            
func testCreatingShare() ...
...
 let (share, _) = try await viewModel.createShare(contact: testContact)   //[Type of expression is  ambiguous without more context

I could be bold and assume this test meant  vm.fetchOrCreateShare() as  it's the only method that might match...

Please update the UnitTest.   Thank  you.

**Comment by sjrmanning** [comment]
Hi David, the `main` branch has been updated with the async version of this sample project and the tests have been updated with it. This should have fixed the issue you were seeing, but feel free to re-open this issue if you still see this behavior. Note that for this project's tests to pass, the device or simulator you run the tests on will need to be logged into an iCloud account.
